### ISSUE TITLE
Update Access

### ISSUE THREAD

**Issue by MGatner** [heroespatchnotes/sdk-php#5]
@stuaroo I need to set the COMPOSER_AUTH secret in order to enable GitHub Action's to use Composer. Could you please update my access to Owner? If you prefer you may restore my current access after the secrets set.

**Comment by MGatner** [comment]
Yeah I actually can't even push changes :O Whenever you get a chance this is preventing release.

**Comment by stuaroo** [comment]
Ok, give it a go now.  That's so weird because you even had full admin access on the fork of heroes-data, but only had Read on this project (and there wasn't a way to grant admin access to the specific project either).

**Comment by MGatner** [comment]
Worked like a charm! That you! Prepping for initial release.
